### ISSUE TITLE
Cannot build mgconsole Debian - Wolverine

### ISSUE THREAD

**Issue by antejavor** [memgraph/mgconsole#40]
Mgconsole build, not working on Wolverine. 

1. Issue I got was: 
![image](https://user-images.githubusercontent.com/18125448/203377229-8442ece0-aaeb-4e3d-afc9-a9ac7842526c.png)
2. Then I added `#include <iomanip>` to `utils.cpp`
3. Try to rebuild again, got this error: 
![image](https://user-images.githubusercontent.com/18125448/203377601-1d0db3f5-de41-46e1-8f47-7af072ea0171.png)

**Comment by DavIvek** [comment]
![Screenshot from 2024-02-23 14-40-06](https://github.com/memgraph/mgconsole/assets/88043717/20ae8400-f74a-4ac1-92fc-445b021034f7)
Looks to me that this issue no longer persists.
