### ISSUE TITLE
can't compile mgconsole on Fedora 37

### ISSUE THREAD

**Issue by Elvino00** [memgraph/mgconsole#46]
I'm trying to compile mgconsole on fedora 37 x64 bit (no arm)  but after writing `make` (so after `cmake -DCMAKE_BUILD_TYPE=Release ..`  successfull)  I get this error:

![image](https://user-images.githubusercontent.com/74961430/221238318-fc45964f-5e01-4785-a4de-0ead4b49a39f.png)

Look at the last three rows. It's the same error as [this one](https://github.com/memgraph/mgclient/issues/51).

**Comment by gitbuda** [comment]
It seems that the static version of `libstdc++` has to be manually installed. Please do this in the following way:
```
sudo dnf install libstdc++-static
```
Once the package is installed, the `make` command should pass.

I'll update the README soon 😄
