### ISSUE TITLE
Building from source error

### ISSUE THREAD

**Issue by alf1303** [memgraph/mgconsole#61]
Getting next error while trying to build mgconsole. Tried with memgraph toolchain and without, same error
```
[ 76%] Building CXX object src/utils/CMakeFiles/utils.dir/thread_pool.cpp.o
In file included from /home/roma/mgconsole/src/utils/thread_pool.hpp:25,
                 from /home/roma/mgconsole/src/utils/thread_pool.cpp:16:
/home/roma/mgconsole/src/utils/synchronized.hpp:18:10: fatal error: concepts: No such file or directory
   18 | #include <concepts>
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [src/utils/CMakeFiles/utils.dir/build.make:90: src/utils/CMakeFiles/utils.dir/thread_pool.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1019: src/utils/CMakeFiles/utils.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```
Ubuntu 20.04 (Windows 10, WSL)

**Comment by gitbuda** [comment]
What's your operating system and default compiler?

Could you delete everything under the build folder, rerun `cmake` and post the output here?

**Comment by alf1303** [comment]
> What's your default compiler?
> 
> Could you delete everything under the build folder, rerun `cmake` and post the output here?

Ubuntu 20.04 (on Windows 10 with WSL)

`(toolchain-v4) roma@DellLapot:~/mgconsole/build$ cmake -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMake build type: Release
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1f")  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/roma/mgconsole/build
(toolchain-v4) roma@DellLapot:~/mgconsole/build$ `

**Comment by alf1303** [comment]
> What's your default compiler?
> 
> Could you delete everything under the build folder, rerun `cmake` and post the output here?

Default compiler is /usr/bin/c++ i guess, not sure how to check correctly.
```
(toolchain-v4) roma@DellLapot:~/mgconsole/build$ update-alternatives --query c++
Name: c++
Link: /usr/bin/c++
Slaves:
 c++.1.gz /usr/share/man/man1/c++.1.gz
Status: auto
Best: /usr/bin/g++
Value: /usr/bin/g++

Alternative: /usr/bin/g++
Priority: 20
Slaves:
 c++.1.gz /usr/share/man/man1/g++.1.gz
```

**Comment by gitbuda** [comment]
Yea, I've noticed that for some reason `cmake` doesn't pick the toolchain compiler (mgconsole doesn't necessarily need compiler from the toolchain, but the default one under Ubuntu 20.04 doesn't work) -> will try to debug that...

Could you try to run the following:
```
mkdir build && cd build
cmake -DCMAKE_C_COMPILER=/opt/toolchain-v4/bin/clang -DCMAKE_CXX_COMPILER=/opt/toolchain-v4/bin/clang++ ..
make
```
?

**Comment by alf1303** [comment]
> cmake -DCMAKE_C_COMPILER=/opt/toolchain-v4/bin/clang -DCMAKE_CXX_COMPILER=/opt/toolchain-v4/bin/clang++ ..

Yes, that worked, thanks
