### ISSUE TITLE
build failed. extra semi-colon 

### ISSUE THREAD

**Issue by msgoff** [memgraph/mgconsole#67]
mgconsole/src/utils/future.hpp +276

builds fine after the semi-colon is removed

**Comment by antejavor** [comment]
Hi @msgoff, 

Thanks for pointing out this one 🙏 . What compiler/setup specifics did you use to build from the source? 

Asking for the sake of understanding because I can see our CI/CD build is working, and it looks like an unnecessary semi-colon, but what tool/compiler is picking this?

**Comment by msgoff** [comment]
Hello @antejavor 

Thank you for the quick response. 

gcc -v
gcc version 10.2.1 20210110 (Debian 10.2.1-6) 

mkdir build; cd build; cmake ..;make

[ 94%] Building CXX object src/CMakeFiles/mgconsole.dir/batch_import.cpp.o
In file included from /mgconsole/src/batch_import.cpp:26:
/mgconsole/src/utils/future.hpp:276:2: error: extra ‘;’ [-Werror=pedantic]
  276 | };  // namespace utils

**Comment by gitbuda** [comment]
@msgoff the fix should be merged to master (hopefully that will help you) 💪
I think we have to improve the compile flags, but that should be done under another PR

**Comment by msgoff** [comment]
@gitbuda 
Thank you!
